<?php

if (function_exists('acf_add_local_field_group')) :

	acf_add_local_field_group(array(
		'key' => 'group_5f64ae6a8d7ac',
		'title' => 'PDF',
		'fields' => array(
			array(
				'key' => 'field_5f902b85ff894',
				'label' => 'Nur für Nutzer X',
				'name' => 'access_by_user',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => 'Dokument nur für nutzer X freigeben',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_5f64ae6a8ef7e',
				'label' => 'Nutzer',
				'name' => 'user',
				'type' => 'user',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5f902b85ff894',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '45',
					'class' => '',
					'id' => '',
				),
				'role' => array(
					0 => 'subscriber',
				),
				'allow_null' => 0,
				'multiple' => 0,
				'return_format' => 'id',
			),

		),
		'location' => array(
			array(
				array(
					'param' => 'attachment',
					'operator' => '==',
					'value' => 'application/pdf',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'acf_after_title',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));

	acf_add_local_field_group(array(
		'key' => 'group_5f612d3c5a953',
		'title' => 'Projektdaten',
		'fields' => array(
			array(
				'key' => 'field_5f8da8f522114',
				'label' => 'Domain',
				'name' => 'domain',
				'type' => 'url',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '33%',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
			),
			array(
				'key' => 'field_5f612d41e8d1a',
				'label' => 'Rendite',
				'name' => 'rendite',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '33%',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5f61367374a65',
				'label' => 'Marktkapitalisierung',
				'name' => 'complete_invest',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '33%',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_5f7dcf78c5b76',
				'label' => 'Einkommensquellen',
				'name' => 'earnings',
				'type' => 'flexible_content',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layouts' => array(
					'layout_5f7dcf8ba84e8' => array(
						'key' => 'layout_5f7dcf8ba84e8',
						'name' => 'cashflow_eranings',
						'label' => 'Einkommensquelle',
						'display' => 'column',
						'sub_fields' => array(
							array(
								'key' => 'field_5f7dcf91c5b77',
								'label' => 'Name',
								'name' => 'cashflow_title',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '30%',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_5f7dda880b4b6',
								'label' => 'Farbe',
								'name' => 'cashflow_earnings_color',
								'type' => 'color_picker',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '20%',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
							),
							array(
								'key' => 'field_5f7dcfe3a85f9',
								'label' => 'Prozentsatz Einkommensquelle',
								'name' => 'cashflow_earnings_procent',
								'type' => 'number',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '20%',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'min' => '',
								'max' => '',
								'step' => '',
							),

						),
						'min' => '',
						'max' => '',
					),
				),
				'button_label' => 'Eintrag hinzufügen',
				'min' => '',
				'max' => '',
			),
			/*
				array(
					'key' => 'field_5f7dde0c21065',
					'label' => 'rendite_pro_user',
					'name' => 'rendite_pro_user',
					'type' => 'flexible_content',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layouts' => array(
						'layout_5f7dde16b85c6' => array(
							'key' => 'layout_5f7dde16b85c6',
							'name' => 'rendite_pro_user',
							'label' => 'rendite_pro_user',
							'display' => 'table',
							'sub_fields' => array(
								array(
									'key' => 'field_5f7dde3221066',
									'label' => 'user',
									'name' => 'user',
									'type' => 'user',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'role' => array(
										0 => 'subscriber',
									),
									'allow_null' => 0,
									'multiple' => 0,
									'return_format' => 'id',
								),
								array(
									'key' => 'field_5f7dde5821067',
									'label' => 'rendite',
									'name' => 'rendite',
									'type' => 'number',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'min' => '',
									'max' => '',
									'step' => '',
								),
							),
							'min' => '',
							'max' => '',
						),
					),
					'button_label' => 'Eintrag hinzufügen',
					'min' => '',
					'max' => '',
				),
				*/
			array(
				'key' => 'field_5fa148a75bf71',
				'label' => 'Projekt PDF',
				'name' => 'docs',
				'type' => 'relationship',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array(
					0 => 'attachment',
				),
				'taxonomy' => '',
				'filters' => array(),
				'elements' => '',
				'min' => '',
				'max' => '',
				'return_format' => 'object',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'projects',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'acf_after_title',
		'style' => 'seamless',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => array(
			0 => 'discussion',
			1 => 'comments',
			2 => 'revisions',
			3 => 'categories',
			4 => 'send-trackbacks',
		),
		'active' => true,
		'description' => '',
	));

	acf_add_local_field_group(array(
		'key' => 'group_5f611364275d8',
		'title' => 'Transactions',
		'fields' => array(
			array(
				'key' => 'field_5f61136429567',
				'label' => 'User',
				'name' => 'user',
				'type' => 'user',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '30%',
					'class' => '',
					'id' => '',
				),
				'role' => '',
				'allow_null' => 0,
				'multiple' => 0,
				'return_format' => 'id',
			),
			
			array(
				'key' => 'field_5f61137361031',
				'label' => 'Projekte',
				'name' => 'projects',
				'type' => 'post_object',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '30%',
					'class' => '',
					'id' => '',
				),
				'post_type' => array(
					0 => 'projects',
				),
				'taxonomy' => '',
				'allow_null' => 0,
				'multiple' => 0,
				'return_format' => 'object',
				'ui' => 1,
			),
			array(
				'key' => 'field_5f611480376bd',
				'label' => 'invest',
				'name' => 'invest',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '20%',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_5f612d41e8d1b',
				'label' => 'Rendite',
				'name' => 'rendite',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '20%',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5f7e214a2fc7a',
				'label' => 'StartDatum',
				'name' => 'start_date',
				'type' => 'date_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'display_format' => 'd/m/Y',
				'return_format' => 'd/m/Y',
				'first_day' => 1,
			),
			array(
				'key' => 'field_5f64d80d1cb42',
				'label' => 'EndDatum',
				'name' => 'end_date',
				'type' => 'date_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'display_format' => 'd/m/Y',
				'return_format' => 'd/m/Y',
				'first_day' => 1,
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'transaction',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'acf_after_title',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));

endif;
